spring:
  application:
    name: fileserver
  datasource:
    url: jdbc:sqlite:fileinfo.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

fileserver:
  chunk-size: 8192
  upload-dir: uploads/
  temp-dir: temp/
